### PR TITLE
Update to uicore 4

### PR DESCRIPTION
**Pull request by santipalenque**
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3049975&fileview=grid

### CODE REVIEW

**Review by smarcet — CHANGES_REQUESTED** [review]
@santipalenque please review comments
much tnanks!

**Review by smarcet — DISMISSED** [review]
LGTM

**Comment by gcutrini** [comment]
@santipalenque LGTM.
But there seems to be a build or style issue that causes image assets to be missing (loader gif, fa icons, QR code image on find ticket page).

**Review by gcutrini — DISMISSED** [review]
LGTM

**Review by smarcet — APPROVED** [review]
LGTM

**Review by gcutrini — APPROVED** [review]

**Pull request merged**
